name: Build and Test library
on: 
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '15.2' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v3
    - name: Run Unit and UI Tests
      run: swift test
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest

    steps:
    - uses: actions/checkout@v3
    - name: SwiftLint
      run: |
        swiftlint --reporter github-actions-logging --strict